--- 
build: 
  script: 
    - "rm -rf output"
    - "pelican content"
    - "pelican content -o output -s pelicanconf.py"
    - "pip install ghp-import"
    - "ghp-import output"
  stage: build
  tags: 
    - ci
    - shell
    - ssh
deploy: 
  script: 
    - git remote set-url origin git@github.com:aldoranx/my-blog.git
     
  stage: deploy
  tags: 
    - ci
    - shell
    - ssh
  when: manual
stages: 
  - test_variable
  - build
  - deploy
test_variable: 
  script: 
    - "echo $USER_GITHUB"
  stage: test_variable
  tags: 
    - ci
    - shell
    - ssh

