--- 
build: 
  script: 
    - "rm -rf output"
    - "pelican content"
    - "pelican content -o output -s pelicanconf.py"
    - "pip install ghp-import"
    - "ghp-import output"
  stage: build
  tags: 
    - ci
    - shell
    - ssh
deploy: 
  script: 
    - "git remote set-url origin git@github.com:aldoranx/my-blog.git"
    - "git checkout master"
    - "git reset --hard 4fdb71d201b32111efa9c0349d69af9274ce6027"
    - "pelican content"
    - "git add ."
    - "git commit -m \"test monday v1\""
    - "git push --force http://$USER_GITHUB:$PASSWORD_GITHUB@github.com:aldoranx/my-blog.gitHEAD:master"
    - "pelican content -o output -s pelicanconf.py\""
    - "pip install ghp-import"
    - "ghp-import output"
  stage: deploy
  tags: 
    - ci
    - shell
    - ssh
  when: manual
stages: 
  - test_variable
  - build
  - deploy
test_variable: 
  script: 
    - "echo $USER_GITHUB"
  stage: test_variable
  tags: 
    - ci
    - shell
    - ssh

