--- 
build: 
  script: 
    - rm -rf output
    - pelican content
    - pelican content -o output -s pelicanconf.py
    - pip install ghp-import
    - ghp-import output
    - git push origin gh-pages
  stage: build
  tags: 
    - ci
    - shell
    - ssh
deploy: 
  script: 
    - cd output;nohup python -m pelican.server &
  stage: deploy
  tags: 
    - ci
    - shell
    - ssh
  when: manual
stages: 
  - build
  - deploy
  
