---
test_variable:
  script:
    - echo $CI_JOB_STAGE
  stage: test
  tags:
    - ci
    - shell
    - ssh
build: 
  script:
    - rm -rf output
    - pelican content
    - pelican content -o output -s pelicanconf.py
    - pip install ghp-import 
    - ghp-import output
  stage: build
  tags: 
    - ci
    - shell
    - ssh
deploy:
  script:
    - echo hello world     
  stage: deploy
  tags: 
    - ci
    - shell
    - ssh
  when: manual
stages:
  - test_variable 
  - build
  - deploy
  
