--- 
build: 
  script: 
    - "rm -rf output"
    - "pelican content"
    - "pelican content -o output -s pelicanconf.py"
    - "pip install ghp-import"
    - "ghp-import output"
  stage: build
  tags: 
    - ci
    - shell
    - ssh
deploy: 
  script: 
    - git config --global user.name "${USER_GITHUB}"
    - git config --global user.email "${GITHUB_USER_EMAIL}"
    - git config --global --list
    - git remote set-url origin git@github.com:aldoranx/my-blog.git
    - git checkout master
    - git reset --hard 4fdb71d201b32111efa9c0349d69af9274ce6027
    - rm -rf output
    - pelican content
    - touch txt.txt
    - git add .
    - git commit -m "add txt.txt"
    - git status
    - pelican content -o output -s pelicanconf.py
    - pip install ghp-import
    - ghp-import output
    - git remote set-url --push origin git@github.com:aldoranx/my-blog.git

  stage: deploy
  tags: 
    - ci
    - shell
    - ssh
  when: manual
stages: 
  - test_variable
  - build
  - deploy
test_variable: 
  script: 
    - "echo $USER_GITHUB"
  stage: test_variable
  tags: 
    - ci
    - shell
    - ssh
 
