--- 
build: 
  script: 
    - "rm -rf output"
    - "pelican content"
    - "pelican content -o output -s pelicanconf.py"
    - "pip install ghp-import"
    - "ghp-import output"
  stage: build
  tags: 
    - ci
    - shell
    - ssh
deploy: 
  script:
    - git push https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/$GITHUB_USER.github.io.git/my-blog HEAD:master
  stage: deploy
  tags: 
    - ci
    - shell
    - ssh
  when: manual
stages: 
  - test_variable
  - build
  - deploy
test_variable: 
  script: 
    - "echo $GITHUB_USER"
  stage: test_variable
  tags: 
    - ci
    - shell
    - ssh

