--- 
build: 
  script:
    - rm -rf output
    - pelican content
    - pelican content -o output -s pelicanconf.py
    - pip install ghp-import 
    - ghp-import output
  stage: build
  tags: 
    - ci
    - shell
    - ssh
deploy:
  before_script:
    - echo "$GITHUB_RSA_PRIVATE"
  script:
    - git remote set-url origin https://github.com/aldoranx/my-blog.git
    - pelican content -o output -s pelicanconf.py
    - ghp-import output
    - git add --all
    - git commit -m "test github pages gitlab"
    - git push -f origin gh-pages
      
  stage: deploy
  tags: 
    - ci
    - shell
    - ssh
  when: manual
stages: 
  - build
  - deploy
  
