---
test_variable:
  script:
    - echo $SSH_PRIVATE_KEY
    - echo $USER_GITHUB
    - echo $PASSWORD_GITHUB
  stage: test_variable
  tags:
    - ci
    - shell
    - ssh
build: 
  script:
    - rm -rf output
    - pelican content
    - pelican content -o output -s pelicanconf.py
    - pip install ghp-import 
    - ghp-import output
  stage: build
  tags: 
    - ci
    - shell
    - ssh
deploy:
  script:
    - echo hello ranx     
  stage: deploy
  tags: 
    - ci
    - shell
    - ssh
  when: manual
stages:
  - test_variable 
  - build
  - deploy
  
