--- 
build: 
  script: 
    - "rm -rf output"
    - "pelican content -o output -s pelicanconf.py"
    - "pip install ghp-import"
    - "ghp-import output"
  stage: build
  tags: 
    - ci
    - shell
    - ssh
deploy: 
  script: 
    - "git remote set-url origin git@git@192.168.121.84:aldo92i/my-blog.git"
    - "ls -a"
  stage: deploy
  tags: 
    - ci
    - shell
    - ssh
  when: manual
stage: 
  - build
  - deploy

