--- 
cuild: 
  script: 
    - git clone --force https://$GITLAB_TOKEN@gitlab.com/192.168.121.84/aldo92i/my-blog.git
    - ls -a
  stage: build
  tags: 
    - ci
    - shell
    - ssh
deploy: 
  script:
    - cd /virtualenvs/pelican/output
    - git add *
    - git commit -m "sunday 20th"
    - git push --force https://$GITHUB_TOKEN@github.com/aldoranx/my-blog.git HEAD:master
  stage: deploy
  tags: 
    - ci
    - shell
    - ssh
  when: manual
stages: 
  - test_variable
  - build
  - deploy
test_variable: 
  script: 
    - "echo $GITHUB_USER"
  stage: test_variable
  tags: 
    - ci
    - shell
    - ssh

