stages:
  - build
  - test
  
build:
  stage: build
  script:
    - echo Hello World

  tags:
    - ci

  when: manual

test:
  stage: test
  script:
    - rm -rf output
    - pelican content
    - cd output; python -m pelican.server
  tags:
    - ci

