stages:
  - build
  - test

build:
  stage: build
  script:
    - echo Hello World

test:
  stage: test
  script:
    - rm -rf output
    - pelican content
    - cd output; python -m pelican.server

   tags:
    - ci

  when: manual
