--- 
branches: 
  only: 
    - master
install: 
  - "pip install pelican ghp-import"
language: python
script: 
  - "cd pelican"
  - "pelican content -o output -s pelicanconf.py"
  - "ghp-import output"
  - "git push origin gh-pages"
tags: 
  - ci
  - shell
  - ssh

