--- 
build: 
  script:
    - echo $USER_GITHUB 
    - rm -rf output
    - pelican content
    - pelican content -o output -s pelicanconf.py
    - pip install ghp-import 
    - ghp-import output
  stage: build
  tags: 
    - ci
    - shell
    - ssh
deploy: 
  script: 
    - ls -a 
  stage: deploy
  tags: 
    - ci
    - shell
    - ssh
  when: manual
stages: 
  - build
  - deploy
  
