---
test_variable:
  stage: test
  script:
    - echo $SSH_PRIVATE_KEY
  tags:
    - ci
    - shell
    - ssh
build: 
  script:
    - rm -rf output
    - pelican content
    - pelican content -o output -s pelicanconf.py
    - pip install ghp-import 
    - ghp-import output
  stage: build
  tags: 
    - ci
    - shell
    - ssh
deploy:
  script:
    -ls -a
      
  stage: deploy
  tags: 
    - ci
    - shell
    - ssh
  when: manual
stages:
  - test_variable 
  - build
  - deploy
  
